CREATE DATABASE IF NOT EXISTS sip_main CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE USER IF NOT EXISTS 'sip_user'@'127.0.0.1' IDENTIFIED BY '123456';
CREATE USER IF NOT EXISTS 'sip_user'@'localhost' IDENTIFIED BY '123456';
GRANT ALL PRIVILEGES ON sip_main.* TO 'sip_user'@'127.0.0.1';
GRANT ALL PRIVILEGES ON sip_main.* TO 'sip_user'@'localhost';
FLUSH PRIVILEGES;
